{% set version = "0.42.0" %}

package:
  name: sqlalchemy-utils
  version: {{ version }}

source:
  # The source url changed for  0.37.*
  url: https://pypi.org/packages/source/S/SQLAlchemy-Utils/sqlalchemy_utils-0.42.0.tar.gz
  sha256: 6d1ecd3eed8b941f0faf8a531f5d5cee7cffa2598fcf8163de8c31c7a417a5e0

build:
  number: 0
  # Intervals is not available on s390x
  skip: true  # [py<39 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0.0
  run:
    - python
    - sqlalchemy >=1.4
    # extras
    - babel >=1.3
    - arrow >=0.3.4
    - pendulum >=2.0.5
    - intervals >=0.7.1
    - phonenumbers >=5.9.2
    - passlib >=1.6,<2.0
    - colour >=0.0.4
    - python-dateutil
    - furl >=0.4.1
    - cryptography >=0.6
    - importlib_metadata  # [py<38]
  run_constrained:
    - arrow >=0.3.4
    - Babel >=1.3
    - colour >=0.0.4
    - cryptography >=0.6
    - intervals >=0.7.1
    - passlib >=1.6,<2.0
    - pendulum >=2.0.5
    - phonenumbers >=5.9.2
    - furl >=0.4.1

test:
  imports:
    - sqlalchemy_utils
    - sqlalchemy_utils.functions
    - sqlalchemy_utils.primitives
    - sqlalchemy_utils.relationships
    - sqlalchemy_utils.types
  # requires:
  #   - pip
  # Skipping because of pendulum
  # commands:
  #   - pip check

about:
  home: https://github.com/kvesteri/sqlalchemy-utils
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Various utility functions for SQLAlchemy
  description: |
    SQLAlchemy-Utils provides custom data types
    and various utility functions for SQLAlchemy.
  dev_url: https://github.com/kvesteri/sqlalchemy-utils
  doc_url: https://sqlalchemy-utils.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - lvoliveira
    - igortg
