{% set version = "0.37.8" %}

package:
  name: sqlalchemy-utils
  version: {{ version }}

source:
  # The source url changed for  0.37.0
  url: https://github.com/kvesteri/sqlalchemy-utils/archive/refs/tags/{{ version }}.tar.gz
  sha256: d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - sqlalchemy >=1.0
    # extras
    - anyjson >=0.3.3
    - babel >=1.3
    - arrow >=0.3.4
    - pendulum >=2.0.5
    - intervals >=0.7.1
    - phonenumbers >=5.9.2
    - passlib >=1.6,<2.0
    - colour >=0.0.4
    - python-dateutil
    - furl >=0.4.1
    - cryptography >=0.6

test:
  imports:
    - sqlalchemy_utils
    - sqlalchemy_utils.functions
    - sqlalchemy_utils.primitives
    - sqlalchemy_utils.relationships
    - sqlalchemy_utils.types

about:
  home: https://github.com/kvesteri/sqlalchemy-utils
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Various utility functions for SQLAlchemy
  dev_url: https://github.com/kvesteri/sqlalchemy-utils
  doc_url: https://sqlalchemy-utils.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - lvoliveira
    - igortg
