travis:
  secure:
    BINSTAR_TOKEN: LsWwsGqeqsfNeCEnOiivG/kxz+QwJAOU6ApOvWvgdBhgFNchnp7S0bi+cpjVsMLKaWHAkrYuaR/z1VFyR8UKjdXwIA8/tJPpGnJlkrb1ZLgy8AxFEU0vkQJdiqzpcepP8pjnSekj8dv6Q9k4ciFUzMFhqoeXuHqaqEz1QrfGxs8sqXpT5CYF0QvEzZSRWEqD03UACPyeEvtZ5R7wlzLgoV7rqT3YGpw/Ow/5BQFrLdeomMYSJuu0Bp7Q2k4uUxq+u0EqOWpMQV3xJa2Ult2pz/+E2MZeFdmxCxfl3hSl5hVYTCEyRBOnh6hY8pT0f2OzskIp7v/Pd4aDwoYVNfMCjrCDZuqqKQTTVmo3T7Cg/JRhn31SYTefvc6oRkoYiXXdBkZiMS1gZt3j5jDcL8QjNXyLn6MidMFaM3+Sfs2yEIEWeM3QXS5Bk0L2U6384CZMFIgwzhLoTxHnycChhX8J/bWEsdPQENFMPc8SVHm5Ukdm4kL1JDeJcnOOjh8UBL1mWzCVsvg5aZZeIn0GSqTHDdgbeaHNw/XMzcO5mak47uBZsct6TNi66FqepGsGhQlylWc+kBPM/eBcyy09MUOnCKZ8eokbZoVvWTMKGeCRpbqzJVcoyuTq8OcybCZZyCB1w/h+TxkQ+PKqmMCoOONjt6qTNX62XHmJSANCIEOaO0w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
